force-app/main/default/objects/Daily_laser__c/Daily_laser__c.object-meta.xml
<CustomObject>
    <label>Daily laser</label>
    <nameField>
        <displayFormat>DSL-{000}</displayFormat>
        <label>Daily Laser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily laser</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_laser__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Daily laser</relationshipLabel>
    <relationshipName>Daily_laser</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_laser__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_laser__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RelatedAccountDSLController.cls
public class RelatedAccountDSLController {
    
    @AuraEnabled
    public static List<Daily_laser__c> retrieveDSL(String recordId){
        system.debug('recordId'+recordId);
        System.debug('DSL'+[select id,name,Amount__c,Account_Name__c,Reason__c,RecordType.Name,RecordTypeId from Daily_laser__c where Account_Name__c =: recordId]);
      return [select id,name,Amount__c,Account_Name__c,Date__c,Reason__c,RecordType.Name,RecordTypeId,Account_Name__r.Name,Createddate from Daily_laser__c where Account_Name__c=: recordId  ORDER BY Createddate DESC];
        // return [SELECT Name, Id, Account.Name, Amount, StageName, CloseDate  FROM Opportunity WHERE  Competitor_1__r.Id = :recordId OR Competitor_2__r.Id = :recordId ];
    }  

}