force-app/main/default/objects/Daily_laser__c/Daily_laser__c.object-meta.xml
<CustomObject>
    <label>Daily laser</label>
    <nameField>
        <displayFormat>DSL-{000}</displayFormat>
        <label>Daily Laser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily laser</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_laser__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Daily laser</relationshipLabel>
    <relationshipName>Daily_laser</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_laser__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_laser__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_laser__c/recordTypes/Inward.recordType-meta.xml
<RecordType>
    <fullName>Inward</fullName>
    <active>true</active>
    <label>Inward</label>
</RecordType>

force-app/main/default/objects/Daily_laser__c/recordTypes/Outward.recordType-meta.xml
<RecordType>
    <fullName>Outward</fullName>
    <active>true</active>
    <label>Outward</label>
</RecordType>

force-app/main/default/classes/listofDSLRecord.cls
public class listofDSLRecord {
    
   	public Account acc {set;get;}
    public listofDSLRecord(ApexPages.StandardController controller) {
        this.acc = (Account)controller.getRecord();
        system.debug('acc-->'+acc);
    }
    
   	public List<Daily_laser__c> getDLInward() {
        //Account a=[select id,name from Program__c where id=:pro.id];
	List<Daily_laser__c> dLIresults = [select id,name,Amount__c,Account_Name__c,Reason__c,RecordType.Name,Date__c,Createddate,
                                RecordTypeId from Daily_laser__c where Account_Name__c=:acc.Id and RecordType.Name='Inward' ORDER BY Createddate DESC ];
	return dLIresults;
	}
	public List<Daily_laser__c> getDLOutward() {
	List<Daily_laser__c> dLOresults = [select id,name,Amount__c,Account_Name__c,Reason__c,RecordType.Name,Date__c,Createddate,
                                RecordTypeId from Daily_laser__c where Account_Name__c=:acc.Id and RecordType.Name='Outward' ORDER BY Createddate DESC];
	return dLOresults;
	} 

}