force-app/main/default/objects/Warehouse_Recip__c/Warehouse_Recip__c.object-meta.xml
<CustomObject>
    <label>Warehouse Receipt</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Recip__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Total_Weight_of_Goods__c *  Rate_Of_Goods__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Avg_Weight__c.field-meta.xml
<CustomField>
    <fullName>Avg_Weight__c</fullName>
    <label>Avg Weight</label>
    <precision>16</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Column_Number__c.field-meta.xml
<CustomField>
    <fullName>Column_Number__c</fullName>
    <label>Column Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Date_of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Purchase__c</fullName>
    <label>Date of Purchase</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Date_Of_Sell__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Sell__c</fullName>
    <label>Date Of Sell</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <label>Item Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Groundnut(भुईमूग)</fullName>
            </value>
            <value>
                <fullName>Sunflower(सूर्यफूल)</fullName>
            </value>
            <value>
                <fullName>Sesame/Til(तीळ/तीळ)</fullName>
            </value>
            <value>
                <fullName>Safflower(करडई)</fullName>
            </value>
            <value>
                <fullName>Linseed(जवस)</fullName>
            </value>
            <value>
                <fullName>Soybean(सोयाबीन)</fullName>
            </value>
            <value>
                <fullName>Rapeseed(रेपसीड)</fullName>
            </value>
            <value>
                <fullName>Mustard(मोहरी)</fullName>
            </value>
            <value>
                <fullName>Wheat(गहू)</fullName>
            </value>
            <value>
                <fullName>Pearl millet(बाजरी)</fullName>
            </value>
            <value>
                <fullName>Finger miller(नाचणी )</fullName>
            </value>
            <value>
                <fullName>Rice(तांदूळ)</fullName>
            </value>
            <value>
                <fullName>Sorghum(ज्वारी)</fullName>
            </value>
            <value>
                <fullName>Barley(सातू)</fullName>
            </value>
            <value>
                <fullName>Maize/corn(मका)</fullName>
            </value>
            <value>
                <fullName>Gram /yellow gram/chickpeas(हरभरा)</fullName>
            </value>
            <value>
                <fullName>Split chickpeas(हरभराडाळ)</fullName>
            </value>
            <value>
                <fullName>Black-eyed beans/ black- eyed pea/ goat pea(चवळी)</fullName>
            </value>
            <value>
                <fullName>Black gram(उडीद)</fullName>
            </value>
            <value>
                <fullName>Split black gram(उडीदडाळ)</fullName>
            </value>
            <value>
                <fullName>Green gram(मुग)</fullName>
            </value>
            <value>
                <fullName>Split green gram(मुगडाळ)</fullName>
            </value>
            <value>
                <fullName>Red Pigeon pea(लाल तुर)</fullName>
            </value>
            <value>
                <fullName>White Piegeon Pea(पांढरी तुर)</fullName>
            </value>
            <value>
                <fullName>Split pigeon pea(तुरडाळ)</fullName>
            </value>
            <value>
                <fullName>Lentil(मसूर)</fullName>
            </value>
            <value>
                <fullName>Split lentil(मसूरडाळ)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Item_Quantity__c</fullName>
    <label>Item Quantity</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Owner_Goods_Sign__c.field-meta.xml
<CustomField>
    <fullName>Owner_Goods_Sign__c</fullName>
    <label>Owner Goods Sign</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <label>Goods Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Rate_Of_Goods__c.field-meta.xml
<CustomField>
    <fullName>Rate_Of_Goods__c</fullName>
    <label>Rate Of Goods</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Rent_of_per_Goods__c.field-meta.xml
<CustomField>
    <fullName>Rent_of_per_Goods__c</fullName>
    <label>Rent of per Goods</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Stage_of_Item__c.field-meta.xml
<CustomField>
    <fullName>Stage_of_Item__c</fullName>
    <label>Stage of Item</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Khari</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inward</fullName>
            </value>
            <value>
                <fullName>Outward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Total_Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Days__c</fullName>
    <formula>Date_Of_Sell__c -  Date_of_Purchase__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Number of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Total_Rent_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Rent_Amount__c</fullName>
    <formula>(( Item_Quantity__c *  Rent_of_per_Goods__c ) / 30 ) *  Total_Number_of_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Rent Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Total_Weight_of_Goods__c.field-meta.xml
<CustomField>
    <fullName>Total_Weight_of_Goods__c</fullName>
    <formula>(Item_Quantity__c  *  Avg_Weight__c ) / 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Weight of Goods</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Type_of_item__c.field-meta.xml
<CustomField>
    <fullName>Type_of_item__c</fullName>
    <label>Type of item</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Super</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Warehouse_Number__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Number__c</fullName>
    <label>Warehouse Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warehouse_Recip__c/fields/Warehouse_Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Receipt_Number__c</fullName>
    <label>Warehouse Receipt Number</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Recepit.cls
public class Recepit {

    public  Warehouse_Recip__c wr{get; set;}
    public Warehouse_Recip__c wrId{get; set;}
     public Recepit(ApexPages.StandardController controller){
         this.wrId = (Warehouse_Recip__c )controller.getRecord();
         wr=[SELECT  OwnerId, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, 
         LastViewedDate, LastReferencedDate, Avg_Weight__c, Column_Number__c, Date_Of_Sell__c, Date_of_Purchase__c, Item_Name__c, 
         Item_Quantity__c, Owner_Goods_Sign__c, Rate_Of_Goods__c, Rent_of_per_Goods__c, Stage_of_Item__c, Stages__c, Type_of_item__c, 
         Warehouse_Number__c, Warehouse_Receipt_Number__c, Amount__c, Total_Number_of_Days__c, Total_Rent_Amount__c, Total_Weight_of_Goods__c, 
         Owner_Name__c, Warehouse_Address__Street__s, Warehouse_Address__City__s, Warehouse_Address__PostalCode__s, Warehouse_Address__StateCode__s, 
         Warehouse_Address__CountryCode__s, Warehouse_Address__Latitude__s, Warehouse_Address__Longitude__s, Warehouse_Address__GeocodeAccuracy__s, 
         Warehouse_Address__c FROM Warehouse_Recip__c where Id=:wrId.Id limit 1
         ];
     }
}